# pytest.ini
[pytest]
# This allows tests to import modules as if they were installed packages, e.g., 'import module1'
pythonpath = src
# Tell pytest to look for tests in the 'test' directory
testpaths = test
# Common settings for test file/function naming conventions
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    # Always measure the 'src' directory
    --cov=src 
    # Always print a summary to the terminal
    --cov-report=term 
    # Generate the HTML report by default
    --cov-report=html
    # Minimum coverage percentage required
    --cov-fail-under=100